### ISSUE TITLE
[FEATURE REQUEST] Custom path definition for output folder

### ISSUE THREAD

**Issue by alessandroperilli** [talesofai/comfyui-browser#1]
This seems like a very useful feature, but a bit more flexibility in terms of output path would make it even better.

It should either read the content of the `--output-directory` that is passed at startup time (not sure is possible) or, preferable, have an entry in the ComfyUI Manager settings menu where you can specify your output dir.

Thanks for considering the request.

**Comment by yaitsbilly** [comment]
I was just about to suggest this, I put all my image into sub folders within the default output folder.

**Comment by tzwm** [comment]
I have used `--output-directory` args. Please update the extension. Thanks for your feedback.

**Comment by alessandroperilli** [comment]
It works perfectly, thank you. This extension is so useful!

**Comment by alessandroperilli** [comment]
@tzwm, the last couple of commits might have broken support for custom paths. 
All of a sudden, my browser looks like this, but I did not change the location of the images:

<img width="1406" alt="Screenshot 2024-01-14 at 11 03 59" src="https://github.com/talesofai/comfyui-browser/assets/9775949/138cd66e-dfca-49ab-9c45-a261f176333d">

Thanks for your support and hard work!

**Comment by tzwm** [comment]
sorry, it is my bug. I will fix it as soon as possible.

**Comment by tzwm** [comment]
Please upgrade to the latest version. sorry for it.

**Comment by alessandroperilli** [comment]
Perfect. Thank you for fixing it so quickly.
