### ISSUE TITLE
workflow不支持中文命名

### ISSUE THREAD

**Issue by NewEpoch2020** [talesofai/comfyui-browser#13]
如果是中文命名,点击加载会提示"No workflow found here", 英文+数字就没问题.

**Comment by tzwm** [comment]
可以给我下使用的系统（windows/macOS/Linux）和中文命名例子吗？我自己没复现出来。

**Comment by NewEpoch2020** [comment]
> 可以给我下使用的系统（windows/macOS/Linux）和中文命名例子吗？我自己没复现出来。
ComfyUI_windows_portable版本
### Loading: ComfyUI-Manager (V1.5.2)
### ComfyUI Revision: 1866 [1b103e0c] | Released on '2023-12-30'
Total VRAM 12287 MB, total RAM 32559 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.1.1+cu121
使用run_nvidia_gpu.bat来启动

**Comment by tzwm** [comment]
@NewEpoch2020 我更新了一下，希望能解决这个问题。可能是 windows 下的编码问题，我现在都尽可能存为 UTF-8 了。可以更新插件后，重新保存工作流试试。
