### ISSUE TITLE
'grep' is not recognized

### ISSUE THREAD

**Issue by rcfcu2000** [talesofai/comfyui-browser#2]
This is a great tool!

On windows, I have experienced an error:
[comfyui-browser] failed
[comfyui-browser] 'grep' is not recognized as an internal or external command,
operable program or batch file.

I will have to modify the code changing "grep -w" to "findstr" since windows platform does not have grep by default.

Maybe add a check of OS and use findstr for windows instead

**Comment by tzwm** [comment]
@rcfcu2000 I have removed `grep`. Please update the extension and try again. Thanks for your feedback.
