### ISSUE TITLE
Not working with ComfyUI Manager and latest Comfyui

### ISSUE THREAD

**Issue by DarKDinDoN** [talesofai/comfyui-browser#20]
Here is the screen in Comfyui Manager:
![image](https://github.com/talesofai/comfyui-browser/assets/1687854/8d4c5011-679e-44df-b064-6ce52a6c2000)

I don't see any relevant logs.

**Comment by DarKDinDoN** [comment]
Found the error. Two missing folders on startup:
- collections
- sources

**Comment by tzwm** [comment]
I have created these two folders on ComfyUI startup. I will add more checks at runtime. Thanks for the feedback.

**Comment by huxiuhan** [comment]
> Found the error. Two missing folders on startup:
> 
> * collections
> * sources

Thanks for debugging.

**Comment by tzwm** [comment]
please upgrade to the latest version and try again. sorry for it.
