### ISSUE TITLE
【问题】关于浏览图片数量问题

### ISSUE THREAD

**Issue by amimi818** [talesofai/comfyui-browser#21]
不知道是不是我的个案问题，我浏览输出图像时，最多只能显示20个图片，且无法进行滚动浏览。

环境：
   Windows11
   Edge/谷歌浏览器
   Comfyui：Released on '2024-01-13'
   comfyui-browser也更新到了13日之后的最新版本

   另，在我mac版本的comfyui下无此问题。

![image](https://github.com/talesofai/comfyui-browser/assets/133093934/aaf25cbc-00b5-4c8f-abe6-fc7806c9cb50)

**Comment by tzwm** [comment]
我去 windows 下试试，我确实平时在 mac 下测试比较多

**Comment by wutao369** [comment]
我也遇到同样的问题。只能显示显示comfyui ——output目录下最近日期的46张图片。

**Comment by wutao369** [comment]
> 我也遇到同样的问题。只能显示显示comfyui ——output目录下最近日期的46张图片。

经测试发现切换到side模式可显示output目录的全部图片

**Comment by tzwm** [comment]
我这两天研究一下，感谢反馈

**Comment by amimi818** [comment]
另外，下面的button位置也有点别扭，而且按钮之间间距太小了。习惯上一般按钮都是居中或右下角。

<img width="1201" alt="image" src="https://github.com/talesofai/comfyui-browser/assets/133093934/15703829-3193-49f0-9aa5-db8954da1824">

**Comment by Stardesign2024** [comment]
<img width="1267" alt="PixPin_2024-04-08_19-10-02" src="https://github.com/talesofai/comfyui-browser/assets/165006259/417f0a51-cfc5-4111-bf18-b758c3014c49">
我甚至不显示按钮！

**Comment by amimi818** [comment]
> <img alt="PixPin_2024-04-08_19-10-02" width="1267" src="https://private-user-images.githubusercontent.com/165006259/320458011-417f0a51-cfc5-4111-bf18-b758c3014c49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTIwODksIm5iZiI6MTcxMjY1MTc4OSwicGF0aCI6Ii8xNjUwMDYyNTkvMzIwNDU4MDExLTQxN2YwYTUxLWNmYzUtNDExMS1iZjE4LWI3NThjMzAxNGM0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwODM2MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzI5MDIxZTU2YjZhYTM2N2M2YWRmNDRiOTcwNmYxNTRiODkxMDdlMDM4MTA3NzVlN2M5ZDFlYzJhNGZkZDIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.c7WKu0NpRX0YEA6ZqjFnHn0hAJGLSOpoUgoi-hfLZXg"> 我甚至不显示按钮！

作者似乎也不太关注这个问题，只好忍痛卸载了
