### ISSUE TITLE
Add support to ipv6 address

### ISSUE THREAD

**Issue by speaknowpotato** [talesofai/comfyui-browser#26]
https://github.com/talesofai/comfyui-browser/blob/main/utils.py#L10

`SERVER_BASE_URL = f'http://{args.listen}:{args.port}'
`
The above code doesn't support ipv6 address. 

it should be 
`SERVER_BASE_URL = f'http://[{args.listen}]:{args.port}'
`

Thanks!

**Comment by tzwm** [comment]
Please upgrade to the new version and try it again. Thanks for the feedback.
