### ISSUE TITLE
[FEATURE REQUEST] Labels for the XYZ Plot

### ISSUE THREAD

**Issue by alessandroperilli** [talesofai/comfyui-browser#28]
As I said on Reddit a few weeks ago, your XYZ Plot node is the elegant and powerful way to plot complex parameter variations in a complex workflow. Thanks for sharing it with the community. 

I'm preparing to include this node in the upcoming [AP Workflow 9.0](https://perilli.com/ai/comfyui/) (it's already in the Early Access 3 prerelease), and I wanted to ask if you could add a way to show arbitrary axis labels. 

It would make the plot easier to read, especially if you are showing the plot to people that didn't prepare the node configuration.

Thank you for considering my request.

**Comment by tzwm** [comment]
@alessandroperilli Thanks for your feedback.
Would this be helpful If I add the display name for the axis to xyz_plot node config?
<img width="432" alt="image" src="https://github.com/talesofai/comfyui-browser/assets/828837/e354ade9-c461-4e38-bc58-5fcfde3b2f7b">

**Comment by alessandroperilli** [comment]
That is a great addition! Thank you. However, I was talking about the presentation of the labels. 
Right now, their name appears at the top left of the grid, in a very inconspicuous way. If the grid is large, and there's scrolling down or right, you don't see them anymore. So, if you want to share the grid on social media, there's no way to easily show what the axes represent. 

It would be better for legibility if the labels could remain always visible at all times, centered in respect to the length of the axis they refer to. 

I have many other ideas of cool and useful things that could be done with the plot, but this seems the most valuable considering how people use these plots.

Thank you.

**Comment by tzwm** [comment]
We pinned the heads of rows and columns. So when you scroll down or right you can see the head always. Is this ok?

<img width="1512" alt="image" src="https://github.com/talesofai/comfyui-browser/assets/828837/cfe6b174-2d48-4154-8233-20ffa71b710f">

**Comment by alessandroperilli** [comment]
That's perfect, thank you.

**Comment by tzwm** [comment]
Please upgrade to the lastest version. We did some updates for xyz plot. And the xyz plot has support the real Z asix niw.

**Comment by alessandroperilli** [comment]
I already did, but I don't see the manual definition of the axis labels in the XYZ Plot node, as you showed in the screenshot above.
