### ISSUE TITLE
Support git sync via token

### ISSUE THREAD

**Issue by Semonxue** [talesofai/comfyui-browser#4]
This node is great for me. Awesome work!

It's good to add support of git sync via token. In gitlab , we can use `https://oauth2:<your-access-token>@gitlab.com/your-username/your-repo.git` to clone and sync files.the `<your-access-token>` is personalized for user from settings. 

In github it looks like `https://<token>@github.com/your-username/your-repo.git`

If input this single line in the comfyui brower's git repository , can save workflows from cloud server like colab.

**Comment by huxiuhan** [comment]
Thanks for your advice! It actually works as you described but we will make it more clear.

**Comment by tzwm** [comment]
@Semonxue  I wrote a wiki for this: https://github.com/talesofai/comfyui-browser/wiki/How-to-use-'Sync'-in-the-'Saves'

Hope this can help you.

**Comment by Semonxue** [comment]
> @Semonxue I wrote a wiki for this: https://github.com/talesofai/comfyui-browser/wiki/How-to-use-'Sync'-in-the-'Saves'
> 
> Hope this can help you.

Its great to read this. I will test it on colab with github & gitlab. Thank you for you work.
