### ISSUE TITLE
not working with new style menue

### ISSUE THREAD

**Issue by speters** [talesofai/comfyui-browser#47]
Thx for this extension.

Unfortunately, this does not work with the [new menue bar](https://github.com/comfyanonymous/ComfyUI/pull/3112), as there is no button.

See screenshots:

"Browser" button visible on old side bar:
![Screenshot 2024-07-08 at 18-03-38 ComfyUI](https://github.com/hayden-fr/ComfyUI-Image-Browsing/assets/1384994/77962f36-0c9e-4473-a8a0-3eab38bf9784)

No "Browser" button on new menue bar:
![Screenshot 2024-07-08 at 18-04-14 ComfyUI](https://github.com/hayden-fr/ComfyUI-Image-Browsing/assets/1384994/67df266c-66a9-4c49-9a96-7d3d2435d7af)

**Comment by willybcode** [comment]
@speters 
Not sure about the availability of the maintainers here, but I made an update to fix that [here](https://github.com/willybcode/comfyui-browser/commit/989c21205f5d6edd2f0e92b9be5b862dbff878f3) and the pr is #66

**Comment by huxiuhan** [comment]
fixed by #66
