### ISSUE TITLE
Request：新的菜单界面可以做一个图标吗

### ISSUE THREAD

**Issue by cilantrocatsoup** [talesofai/comfyui-browser#57]
新的菜单界面整体更简介一点，目前要使用插件只能使用老的菜单界面
![PixPin_2024-08-12_22-49-07](https://github.com/user-attachments/assets/ce58f70e-23ac-473c-a50b-8f1468b976fe)

![PixPin_2024-08-12_22-50-02](https://github.com/user-attachments/assets/982ec43e-a33a-470d-9a52-88df724cdd53)

**Comment by sunnysnake** [comment]
按b键不是更方便吗？

**Comment by cilantrocatsoup** [comment]
> 按b键不是更方便吗？

忘了有这功能了，一直在侧边打开的...

**Comment by huxiuhan** [comment]
fixed by #66
